from pydantic import BaseModel, Field
from typing import List, Optional

# --- 1. Schema for Raw Incoming Feedback ---
class RawFeedback(BaseModel):
    id: str = Field(..., description="Unique ID for the feedback item.")
    source: str = Field(..., description="e.g., 'Google Review', 'In-App Chat', 'Survey'")
    text: str = Field(..., description="The raw, unedited text of the feedback.")
    timestamp: str = Field(..., description="ISO 8601 timestamp.")

# --- 2. Schema for the Root Cause Insight (AI Output) ---
class RootCauseInsight(BaseModel):
    department: str = Field(..., description="Relevant department (e.g., Housekeeping, F&B, Engineering).")
    root_cause_summary: str = Field(..., description="The synthesized core operational failure.")
    urgency_score: int = Field(..., description="1 (Low) to 5 (Critical).")

# --- 3. Schema for the Automated Task Ticket (AI Output) ---
class TaskTicket(BaseModel):
    task_id: Optional[str] = Field(None, description="Unique ID for the task (set by API).")
    description: str = Field(..., description="Actionable instruction for staff.")
    assigned_role: str = Field(..., description="The role or staff member to assign the task to.")
    priority: str = Field(..., description="Priority: 'Critical', 'High', 'Routine'.")
    status: str = Field("Pending", description="Status: 'Pending', 'In Progress', 'Complete'.")

# --- 4. Schema for AI-Drafted Response ---
class AITextDraft(BaseModel):
    original_feedback_id: str = Field(..., description="The ID of the feedback the response is for.")
    draft_text: str = Field(..., description="The full, polite, and personalized draft response.")
    sentiment_target: str = Field(..., description="The sentiment of the original feedback.")

# --- 5. Combined Synthesis Output ---
class SynthesisOutput(BaseModel):
    insights: List[RootCauseInsight]
    tasks_to_create: List[TaskTicket]
    drafted_responses: List[AITextDraft]

# --- 6. Schema for updating a task status ---
class TaskStatusUpdate(BaseModel):
    priority: Optional[str] = None
    assigned_role: Optional[str] = None
    status: Optional[str] = None
    
    # In guestsense-api/app/models.py
from pydantic import BaseModel
from typing import Literal

# ... (Existing Pydantic models like RawFeedback, TaskTicket, etc. above)

# --- Insight Model ---
class Insight(BaseModel):
    """
    Represents a high-level, synthesized insight derived from customer feedback.
    """
    id: str | None = None # Will be generated by the DB (main.py)
    text: str
    sentiment: Literal['Positive', 'Negative', 'Neutral']